"""Added status field

Revision ID: 8187bdf2f743
Revises: 
Create Date: 2025-06-14 15:11:46.861778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8187bdf2f743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rm_counselings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('ultksp_counselings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ultksp_counselings', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('rm_counselings', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
